# Generated by Django 5.2.2 on 2025-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturatask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturatask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
