# Generated by Django 5.2.2 on 2025-07-06 03:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fatura_downloaded_at_fatura_valor_fatura_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faturatask',
            options={},
        ),
        migrations.RemoveField(
            model_name='faturatask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faturatask',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fatura',
            name='file',
            field=models.FileField(default=1, max_length=500, upload_to=api.models.fatura_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faturatask',
            name='unidade_consumidora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_tasks', to='api.unidadeconsumidora'),
        ),
        migrations.CreateModel(
            name='FaturaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.fatura')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.faturatask')),
            ],
        ),
    ]
