# docker-compose.yml
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      # Use a bind mount to map the host directory directly to the container
      - ./backend/media:/app/media 
    # A porta 8000 não precisa mais ser exposta para o host,
    # apenas para a rede interna do Docker, o que é o padrão.
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # Map the same host directory to the Nginx container
      - ./backend/media:/app/media 
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge